Add sdk 8.0 feature
zoyi/channel-plugin-ios pull request #222
Opened 2020-08-13 04:39 UTC by jam0128

2020-08-20 09:07 UTC, zoyi-jin requested changes

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelPluginSettings.swift
> +        }
따로 함수로 빼면 좋을듯?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelPluginSettings.swift
> +      }
따로 함수로 빼면 좋을듯?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/Actions/UserChatActions.swift
> +      "/terms_user?plugin_key=" + (ChannelIO.isNewVersion ? ChannelIO.bootConfig?.pluginKey ?? "" : ChannelIO.settings?.pluginKey ?? "")
줄넘김

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +    ChannelIO.isNewVersion ? ChannelIO.hideMessenger(animated: false) : ChannelIO.close(animated: false)
줄넘김.
그리고 return 받는게 없어서 if else가 더 나아보입니다.

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +              router.pushChat(with: userChatId, text: message, isOpenChat: isOpenChat, animated: animated, from: loungeView)
줄내림

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +        controller.showUserChat(userChatId: userChatId, text: message ?? "", isOpenChat: isOpenChat)
줄 걸치지 않나요?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +        router.pushChat(with: userChatId, text: message, isOpenChat: isOpenChat, animated: animated, from: loungeView)
줄내림

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +        let loungeView = LoungeRouter.createModule(with: userChatId, text: message, isOpenChat: isOpenChat)
줄내림

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    (ChannelIO.settings?.debugMode == true && !ChannelIO.isNewVersion) ||
|| 앞에서 내리는게 맞지 않을까요?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +        ChannelIO.baseNavigation == nil else {
else 내려주세용

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +        ChannelIO.launcherView?.alpha == 0 {
|| 앞에서 내려주세융

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +        let topController = CHUtils.getTopController() else {
else 내려주세요

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard ChannelIO.baseNavigation != nil else { completion?(); return }
묶어도 될듯?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard let topController = CHUtils.getTopController() else { return }
합쳐도 될듯

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +  public class func openChat(with chatId: String?, message: String?, animated: Bool) {
message 안쓰는중

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    }
로직 확인해주세요

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard let userChatId = userInfo["chatId"] as? String else { return }
합쳐주세요

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelPluginSettings.swift
> +    let stage = ChannelStage(rawValue: aDecoder.decodeInteger(forKey: BootConfigKey.stage)) ?? .production
줄넘김 처리 확인해주세요

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/Models.swift
> +    let position = ChannelButtonPosition(rawValue: aDecoder.decodeInteger(forKey: "position")) ?? .right
줄넘김 확인

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/Models/CHAssets.swift
> +      guard let bundle = Bundle.init(path: path) else { return "" }
하나로 합쳐주세요

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/VIPER/UserChat/UserChatPresenter.swift
> +      ChannelIO.delegate?.onUrlClicked?(url: url) : ChannelIO.delegate?.onClickChatLink?(url: url)
```
let shouldHandle = ChannelIO.isNewVersion 
? ChannelIO.delegate?.onUrlClicked?(url: url) : ChannelIO.delegate?.onClickChatLink?(url: url)
```
이 맞지 않을지?

2020-08-20 09:07 UTC, zoyi-jin commented on ChannelIO/Source/Views/ChatNotificationView/PopupInAppNotificationView.swift
> +        ChannelIO.delegate?.onUrlClicked?(url: URL) : ChannelIO.delegate?.onClickChatLink?(url: URL)
? 밑으로 내리는게 맞는것같아요

2020-08-25 11:09 UTC, zoyi-jin requested changes

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/Actions/UserChatActions.swift
> +        ChannelIO.bootConfig?.pluginKey ?? "" : ChannelIO.settings?.pluginKey ?? "")
https://github.com/channel-io/ios-convention-guide#연산자-줄내림-규칙

+ 앞에서 줄내림
? 위치

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +            }).disposed(by: disposeBag)
뒤로 빼기 가능?

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
밖으로 뺄 수 있는지 확인

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelPluginSettings.swift
> +      ) ?? .device
들여쓰기

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +      })
completion 밖으로

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard ChannelIO.isValidStatus,
줄내림

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard ChannelIO.isValidStatus,
줄내림

2020-08-25 11:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +    guard let userChatId = userInfo["chatId"] as? String else { return }
안합치는 이유가 있을까요?

2020-08-26 06:51 UTC, jam0128 commented on ChannelIO/Source/Actions/UserChatActions.swift
> +        ChannelIO.bootConfig?.pluginKey ?? "" : ChannelIO.settings?.pluginKey ?? "")
깃헙링크다니깐 좋네여

2020-08-26 07:58 UTC, jam0128 commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
> +            }).disposed(by: disposeBag)
이거 불가능입니다. 에러헨들링도다르고, 중간에 리턴로직들이 섞여있어서 다르게 동작해요

2020-08-26 07:59 UTC, jam0128 commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
뭘밖으로뺀다는거죵

2020-08-26 08:00 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO+Helper.swift
onNext였는데, 다르다면 패스

2020-09-02 07:09 UTC, zoyi-jin requested changes

2020-09-02 07:09 UTC, zoyi-jin commented on ChannelIO/Source/VIPER/Lounge/LoungePresenter.swift
> +        animated: false, from: view
줄내림

2020-09-02 07:09 UTC, zoyi-jin commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +      ChannelIO.showMessenger(animated: animated)
이건 좀 다른 얘기인데,
Android는 ChannelIO.showMessenger 등의 함수에 animated가 없는데 얘기 된 내용인지요?

2020-09-02 07:09 UTC, jam0128 commented on ChannelIO/Source/VIPER/Lounge/LoungePresenter.swift
> +        animated: false, from: view
홀리..

2020-09-02 07:10 UTC, jam0128 commented on ChannelIO/Source/ChannelIO/ChannelIO.swift
> +      ChannelIO.showMessenger(animated: animated)
음..이건 이전닥스에도안되있어서 그냥한감이있네요 얘기는해볼게요 미카랑

2020-09-03 09:18 UTC, zoyi-jin requested changes

2020-09-03 09:18 UTC, zoyi-jin commented on ChannelIO/Source/Reducers/BotReducer.swift
> +    if let push = action.payload as? CHPopup {
헤헿

2020-09-08 04:41 UTC, zoyi-jin commented
onHideMessenger callback 지우기

2020-10-05 13:28 UTC, merged